[features]
seeds = false
skip-lint = false
[programs.localnet]
sharp_blog = "jpzJx8y4nq7vEvjap3ow8AkqaJtySnpEA1vqJb7WW2Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sharp/finalTask/wallet/blog.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
